name: Gradle CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Check Docker and Docker Compose availability
        run: |
          echo "== Docker =="
          docker --version || echo "Docker not found"
          echo
          echo "== Docker Compose =="
          docker compose version || echo "Docker Compose not found"
          echo
          echo "== Docker Socket =="
          ls -l /var/run/docker.sock || echo "Docker socket missing"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Test Stage
      - name: Run tests
        run: ./gradlew clean test

      # Build Stage
      - name: Build project
        run: ./gradlew build

      # SonarQube Cloud Scan Stage
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
